name = "SolitonsJulia"
uuid = "6e39aff5-d406-4851-b9b6-3a7fe1ff084d"
authors = ["Miguel Ayala <miguel.guadarramaayala@mail.mcgill.ca>"]
version = "0.1.0"

[deps]
RadiiPolynomial = "f2081a94-c849-46b6-8dc9-07bb90ed72a9"
